#!/bin/sh

URI="http://${HOST}:${PORT}/healthz"

if [ "${SKIP_HEALTHCHECK}" != "true" ]; then
  wget --server-response --spider --quiet "$URI" 2>&1 | awk 'NR==1{print $2}' | grep 200 > /dev/null
  if [ 0 != $? ]; then
    exit 1
  fi

  exit 0
fi